---
  - name: Install vsftpd
    apt: name=vsftpd state=present

  - name: Copy config file
    copy: src=vsftpd.conf dest=/etc/vsftpd.conf

  - name: Create chroot_list
    template: src=vsftpd.chroot_list.j2 dest=/etc/vsftpd.chroot_list
    notify: restart vsftpd