---
  - name: install Apache server
    apt:
       name: "apache2"
       state: present
    notify:
    - restart apache

  - name: ensure apache is started and starts on reboot
    service:
      name: "apache2"
      state: started
      enabled: yes

  - name: enable rewrite module
    apache2_module:
      name: rewrite
      state: present

  - name: disable default site
    shell: a2dissite 000-default
