---
- hosts: wordpress
  become: yes
  vars:
    wordpress_user: wordpress
    backup_dir: "/data/backup"
  tasks:
  - name: Create admintools folder
    file:
      path: /opt/admintools/backup-wordpress
      state: directory
      owner: '{{ wordpress_user }}'
      group: '{{ wordpress_user }}'
      mode: '755'

  - name: Copy restore scripts files
    copy:
      src: "{{ item }}"
      dest: "/opt/admintools/backup-wordpress"
      owner: '{{ wordpress_user }}'
      group: '{{ wordpress_user }}'
    with_items:
    - create-key.py
    - encrypt.py
    - restore-wp.py
    - backup-wp.py
    - tools.py
    - requirements.txt

  - name: Copy configuration files
    copy:
      src: "{{ item }}"
      dest: "/etc/"
      owner: '{{ wordpress_user }}'
      group: '{{ wordpress_user }}'
    with_items:
    - AES.key
    - backup-wp.conf

  - name: install setuptools
    apt:
      name: python3-setuptools
      state: present

  - name: install pip
    apt:
      name: python3-pip
      state: present

  - name: Install Python requirements
    pip:
      requirements: "/opt/admintools/backup-wordpress/requirements.txt"

  - name: First ensure that backup dir exist
    file:
      path: "{{ backup_dir }}"
      state: directory
      owner: '{{ wordpress_user }}'
      group: '{{ wordpress_user }}'
      mode: '775'

  - name: Create crontab for backup
    cron:
      name: "daily backup"
      minute: "20"
      hour: "3"
      user: '{{ wordpress_user }}'
      job: "python3 /opt/admintools/backup-wordpress/backup-wp.py"