---
php_extensions:
  - libapache2-mod-php7.3
  - php-common
  - php7.3
  - php7.3-cli
  - php7.3-common
  - php7.3-curl
  - php7.3-gd
  - php7.3-intl
  - php7.3-json
  - php7.3-ldap
  - php7.3-mbstring
  - php7.3-mysql
  - php7.3-opcache
  - php7.3-readline
  - php7.3-soap
  - php7.3-soap
  - php7.3-xml
  - php7.3-xmlrpc
  - php7.3-zip